# Dependencies
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
pygments: true

# Permalinks
permalink: pretty

# Setup
title: Alexei Núñez
tagline: "Explore with me"
description: "A blog with a focus on software development and technology."
url: alexeinunez.com
baseurl: /
paginate: 5

author:
  name: "Alexei Núñez"
  url: https://twitter.com/AlexeiNunez
